jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x86
    - continue-on-error: true
      name: Build HMCLauncher
      run: msbuild /p:Configuration=Release /t:Rebuild /verbosity:detailed .\HMCLauncher\
    - continue-on-error: true
      name: Copy HMCLauncher to assets
      run: Copy-Item .\HMCLauncher\Release\HMCLauncher.exe -Destination .\HMCL\src\main\resources\assets\HMCLauncher.exe
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-package: jdk+fx
        java-version: '11'
    - continue-on-error: true
      env:
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        MICROSOFT_AUTH_ID: ${{ secrets.MICROSOFT_AUTH_ID }}
        MICROSOFT_AUTH_SECRET: ${{ secrets.MICROSOFT_AUTH_SECRET }}
      name: Build with Gradle
      run: .\gradlew makeExecutables --no-daemon
    - continue-on-error: true
      name: Get short SHA
      run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 7))" >> $env:GITHUB_ENV
    - continue-on-error: true
      name: Copy HMCLauncher to libs
      run: Copy-Item .\HMCLauncher\Release\HMCLauncher.exe -Destination .\HMCL\build\libs\HMCLauncher.exe
    - continue-on-error: true
      name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HMCLauncher-${{ env.SHORT_SHA }}
        path: HMCL/build/libs/*.exe
name: Build HMCLauncher
on:
  repository_dispatch:
    types: trigger-ga___build-launcher.yml
