jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-package: jdk+fx
        java-version: '11'
    - continue-on-error: true
      env:
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        MICROSOFT_AUTH_ID: ${{ secrets.MICROSOFT_AUTH_ID }}
        MICROSOFT_AUTH_SECRET: ${{ secrets.MICROSOFT_AUTH_SECRET }}
      name: Build with Gradle
      run: ./gradlew build --no-daemon
    - continue-on-error: true
      name: Get short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
    - continue-on-error: true
      name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HMCL-${{ env.SHORT_SHA }}
        path: HMCL/build/libs
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
